package commands

import (
	"context"
	"errors"
	"strings"

	"github.com.br/lucas-mezencio/pdsi1/internal/application"
	"github.com.br/lucas-mezencio/pdsi1/internal/domain/doctor"
)

// CreateDoctorCommand holds data to create a new doctor.
//
// Like CreateUserCommand, firebase_id is server-generated by the
// AuthenticationProvider; firebase fields are NOT accepted as input.
type CreateDoctorCommand struct {
	Name          string
	Email         string
	Phone         string
	Password      string
	Specialty     string
	LicenseNumber string
}

// UpdateDoctorCommand holds data to update a doctor.
type UpdateDoctorCommand struct {
	ID        string
	Name      string
	Email     string
	Phone     string
	Specialty string
}

// DeleteDoctorCommand removes a doctor.
type DeleteDoctorCommand struct {
	ID string
}

// DoctorCommandHandler handles doctor write operations.
type DoctorCommandHandler struct {
	repo         doctor.Repository
	authProvider AuthenticationProvider
}

// NewDoctorCommandHandler creates a DoctorCommandHandler.
func NewDoctorCommandHandler(repo doctor.Repository, authProvider AuthenticationProvider) *DoctorCommandHandler {
	return &DoctorCommandHandler{repo: repo, authProvider: authProvider}
}

// Create creates a new doctor.
//
// The flow auto-provisions the corresponding Firebase Auth user via the
// configured AuthenticationProvider. firebase_id is server-generated from
// Firebase.
func (h *DoctorCommandHandler) Create(ctx context.Context, cmd CreateDoctorCommand) (*doctor.Doctor, error) {
	if h.authProvider == nil {
		return nil, application.ErrAuthNotConfigured
	}
	if strings.TrimSpace(cmd.Name) == "" ||
		strings.TrimSpace(cmd.Email) == "" ||
		strings.TrimSpace(cmd.Phone) == "" ||
		strings.TrimSpace(cmd.Password) == "" ||
		strings.TrimSpace(cmd.LicenseNumber) == "" {
		return nil, application.ErrInvalidInput
	}
	email := strings.TrimSpace(cmd.Email)
	license := strings.TrimSpace(cmd.LicenseNumber)

	if _, err := h.repo.FindByEmail(ctx, email); err == nil {
		return nil, application.ErrEmailAlreadyInUse
	} else if !errors.Is(err, doctor.ErrDoctorNotFound) {
		return nil, err
	}
	if _, err := h.repo.FindByLicenseNumber(ctx, license); err == nil {
		return nil, application.ErrLicenseAlreadyInUse
	} else if !errors.Is(err, doctor.ErrDoctorNotFound) {
		return nil, err
	}

	firebaseID, err := h.authProvider.CreateUser(ctx, email, cmd.Password)
	if err != nil {
		return nil, err
	}

	newDoctor, err := doctor.NewDoctor(
		strings.TrimSpace(cmd.Name),
		email,
		strings.TrimSpace(cmd.Phone),
		strings.TrimSpace(cmd.Specialty),
		license,
	)
	if err != nil {
		_ = h.authProvider.DeleteUser(ctx, firebaseID)
		return nil, err
	}
	newDoctor.LinkFirebaseAccount(firebaseID)

	if err := h.repo.Save(ctx, newDoctor); err != nil {
		_ = h.authProvider.DeleteUser(ctx, firebaseID)
		return nil, err
	}

	return newDoctor, nil
}

// Update updates an existing doctor.
func (h *DoctorCommandHandler) Update(ctx context.Context, cmd UpdateDoctorCommand) (*doctor.Doctor, error) {
	if cmd.ID == "" {
		return nil, application.ErrInvalidInput
	}

	entity, err := h.repo.FindByID(ctx, cmd.ID)
	if err != nil {
		if errors.Is(err, doctor.ErrDoctorNotFound) {
			return nil, application.ErrDoctorNotFound
		}
		return nil, err
	}

	if err := entity.Update(cmd.Name, cmd.Email, cmd.Phone, cmd.Specialty); err != nil {
		return nil, err
	}

	if err := h.repo.Save(ctx, entity); err != nil {
		return nil, err
	}

	return entity, nil
}

// Delete removes a doctor.
func (h *DoctorCommandHandler) Delete(ctx context.Context, cmd DeleteDoctorCommand) error {
	if cmd.ID == "" {
		return application.ErrInvalidInput
	}

	exists, err := h.repo.Exists(ctx, cmd.ID)
	if err != nil {
		return err
	}
	if !exists {
		return application.ErrDoctorNotFound
	}

	return h.repo.Delete(ctx, cmd.ID)
}
